version: "3.7"

services:
  app:
    image: laravel-www
    container_name: laravel-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes: 
      - .:/var/www/html
    ports: 
      - 8080:80
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7.29
    container_name: laravel-mysql
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes: 
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306

volumes: 
  mysql:
    driver: "local"