version: "3.7"

services:
  app:
    image: laravel-www
    container_name: laravel-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
      - redis
    environment:
      CONTAINER_ROLE: app

  scheduler:
    image: laravel-www
    container_name: laravel-scheduler
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - mysql
      - redis
    environment:
      CONTAINER_ROLE: scheduler

  queue:
    image: laravel-www
    container_name: laravel-queue
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - mysql
      - redis
    environment:
      CONTAINER_ROLE: queue
  mysql:
    image: mysql:5.7.29
    container_name: laravel-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
  redis:
    container_name: laravel-redis
    image: redis:5.0-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
